# List of dependencies for generating visualizations for YOLOv3
name: yolov3-vis
dependencies:
  - absl-py                   0.7.1                    
  - astor                     0.8.0                    
  - astropy                   3.2.1                    
  - blas                      1.0                         
  - ca-certificates           2019.5.15                     
  - certifi                   2019.6.16                
  - cycler                    0.10.0           
  - decorator                 4.4.0                    
  - freetype                  2.9.1                
  - gast                      0.2.2                    
  - google-pasta              0.1.7                    
  - grpcio                    1.22.0                   
  - h5py                      2.9.0                    
  - icc_rt                    2019.0.0             
  - icu                       58.2                 
  - imageio                   2.5.0                    
  - intel-openmp              2019.4                      
  - jpeg                      9b                   
  - keras                     2.2.4                    
  - keras-applications        1.0.8                    
  - keras-preprocessing       1.1.0                    
  - keras-vis                 0.5.0                    
  - kiwisolver                1.1.0            
  - libpng                    1.6.37               
  - libtiff                   4.0.10               
  - markdown                  3.1.1                    
  - matplotlib                3.1.0            
  - mkl                       2019.4                      
  - mkl_fft                   1.0.12           
  - mkl_random                1.0.2            
  - networkx                  2.3                      
  - numpy                     1.17.0                   
  - numpy-base                1.16.4           
  - olefile                   0.46                     
  - opencv-python             4.1.0.25                 
  - openssl                   1.1.1c               
  - pillow                    6.1.0            
  - pip                       19.1.1                   
  - protobuf                  3.9.0                    
  - pyparsing                 2.4.0                      
  - pyqt                      5.9.2            
  - python                    3.6.4                
  - python-dateutil           2.8.0                    
  - pytz                      2019.1                     
  - pywavelets                1.0.3                    
  - pyyaml                    5.1.1                    
  - qt                        5.9.7            
  - scikit-image              0.15.0                   
  - scipy                     1.3.0                    
  - setuptools                41.0.1                   
  - sip                       4.19.8           
  - six                       1.12.0                   
  - sqlite                    3.29.0               
  - tensorboard               1.14.0                   
  - tensorflow                1.14.0                   
  - tensorflow-estimator      1.14.0                   
  - termcolor                 1.1.0                    
  - tk                        8.6.8                
  - tornado                   6.0.3            
  - tqdm                      4.32.2                   
  - vc                        14.1                 
  - vs2015_runtime            14.15.26706          
  - werkzeug                  0.15.5                   
  - wheel                     0.33.4                   
  - wincertstore              0.2              
  - wrapt                     1.11.2                   
  - xz                        5.2.4                
  - zlib                      1.2.11               
  - zstd                      1.3.7
  - pip
  - pip:
    - absl-py              0.7.1
    - astor                0.8.0
    - astropy              3.2.1
    - certifi              2019.6.16
    - cycler               0.10.0
    - decorator            4.4.0
    - gast                 0.2.2
    - google-pasta         0.1.7
    - grpcio               1.22.0
    - h5py                 2.9.0
    - imageio              2.5.0
    - Keras                2.2.4
    - Keras-Applications   1.0.8
    - Keras-Preprocessing  1.1.0
    - keras-vis            0.5.0
    - kiwisolver           1.1.0
    - Markdown             3.1.1
    - matplotlib           3.1.0
    - mkl-fft              1.0.12
    - mkl-random           1.0.2
    - networkx             2.3
    - numpy                1.17.0
    - olefile              0.46
    - opencv-python        4.1.0.25
    - Pillow               6.1.0
    - pip                  19.1.1
    - protobuf             3.9.0
    - pyparsing            2.4.0
    - python-dateutil      2.8.0
    - pytz                 2019.1
    - PyWavelets           1.0.3
    - PyYAML               5.1.1
    - scikit-image         0.15.0
    - scipy                1.3.0
    - setuptools           41.0.1
    - six                  1.12.0
    - tensorboard          1.14.0
    - tensorflow           1.14.0
    - tensorflow-estimator 1.14.0
    - termcolor            1.1.0
    - tornado              6.0.3
    - tqdm                 4.32.2
    - Werkzeug             0.15.5
    - wheel                0.33.4
    - wincertstore         0.2
    - wrapt                1.11.2